### ISSUE TITLE
NodeWrapper

### ISSUE THREAD

**Issue by ClaudiaZarzuela** [UCM-FDI-DISIA/EDEN#37]
Pensar y crear la clase Node del renderWrapper que transforma nuestros vectores y quaterniones a los de ogre, permite hacer las funcionalidades basicas escogidas para cada nodo y  contiene un unorderedMap que asocia entidades con nodos para mantener la abstracción de ogre respecto al motor

**Comment by DavidRainder** [comment]
Revisado!
