### ISSUE TITLE
Inicialización de Ogre

### ISSUE THREAD

**Issue by Migram05** [UCM-FDI-DISIA/EDEN#5]
Una vez haya una primera versión del bucle principal funcionando, inicializar Ogre root y crear una ventana de Ogre. Dicha ventana tiene que poder estar abierta hasta que se termine el bucle principal. Al terminar el bucle principal, la ventana se cierra y toda la memoria reservada se libera.

Además, investigar qué partes de Ogre nos interesa compilar y cuáles no; y ver si nos interesa cargar los plugins puestos en el archivo de configuración plugins.cfg

- [ #16 ]

**Comment by DavidRainder** [comment]
Revisado!
